rm(list=ls())
library(tidyverse)
library(conflicted)
library(elbird)
library(tidytext)
library(modelsummary)
library(epubr)
library(rvest)
library(wordcloud)
library(tidylo)
library(openxlsx)
library(skimr)
library(stm)
library(lubridate)
library(readxl)
library(keyATM)
library(quanteda)
library(readtext)
conflict_prefer('tokenize','elbird')
conflict_prefer('filter','dplyr')

petitions = readtext("petitions_2019-08.json", text_field='content', docid_field='petition_idx')
head(petitions)

test <- corpus(petitions,text_field = 'text')
